#!/usr/bin/env bash

# make sure this script is run with sudo
if [ "$EUID" -ne 0 ]
  then printf "Use sudo to run this script.\n"
  exit
fi

# go to root directory
cd /

source /home/pi/OC-DigitalSignage/config.sh

# create necessary files and directories
# NOTE: this does not use the config variables
mkdir "$JSONPATH"
mkdir "$VIDEOPATH"
touch /home/pi/OC-DigitalSignage/{playlist.txt,fetch.log}
touch "$JSONPATH/file.json"

# make sure the pi user owns all the new files
chown -R pi:pi /home/pi/OC-DigitalSignage/

# begin user configuration session
read -p "Do you wish to edit the config? (y/n) " yn
case $yn in
    [Yy]* ) nano /home/pi/OC-DigitalSignage/config.sh;
esac

# configure crontab 
# write directly to /var/spool/cron/crontabs/root if this doesn't work
(crontab -u root; printf "*/15 * * * * /home/pi/OC-DigitalSignage/push && date +\%Y-\%m-\%d\ \%H:\%M:\%S > /home/pi/OC-DigitalSignage/last_cron\n0 4 * * * sudo /sbin/shutdown -r now && date +\%Y-\%m-\%d\ \%H:\%M:\%S > /home/pi/OC-DigitalSignage/last_cron\n") | crontab -

# start fetching when the desktop environment loads
echo "@/home/pi/OC-DigitalSignage/fetch" >> /etc/xdg/lxsession/LXDE-pi/autostart

# update package repository
apt-get update

# install necessary packages
apt-get install jq youtube-dl bc mpv -Y

read -p "Restart? (y/n) " yn
case $yn in
    [Yy]* ) reboot;
esac

exit 0;
